### ISSUE TITLE
Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 26 declared in library [com.iteratehq:iterate:1.1.5]

### ISSUE THREAD

**Issue by LumisD** [iteratehq/iterate-android#63]
I cannot increase `minSdkVersion ` to 26 as we are targeting wide range of android phones.
How to resolve this issue?

**Comment by LumisD** [comment]
I applied older version 1.1.4 and it builds

**Comment by Daphne-CoffeeIT** [comment]
Applying 1.1.4 indeed resolves the issue, but this also means that a lot of developers probably can't update Iterate anymore for a few years (since it will still take a few years before the `minSdkVersion` of widely used apps can be increased to 26). I'm wondering whether Iterate will provide a backwards compatible solution or not.

**Comment by msingleton** [comment]
Thanks Lumis and Daphne, we'll take another look at the decision to update the minSdkVersion and get back to you soon

**Comment by msingleton** [comment]
We're going to go ahead and go back to supporting version 21, aiming to have that out in the next ~3 weeks, thanks again for the heads up

**Comment by Daphne-CoffeeIT** [comment]
Any updates?

**Comment by LumisD** [comment]
no updates as I quit a project where I worked with it

**Comment by msingleton** [comment]
@Daphne-CoffeeIT appologies for the long delay, we will be releasing a version restoring the minSdk back to 21. You can expect it within the next 2-3 weeks (actually this time). We had discovered some bugs with the implementation that sidetracked us

**Comment by msingleton** [comment]
@Daphne-CoffeeIT it's live now, let us know if you hit any issues with the upgrade and thanks for the patience

**Comment by Daphne-CoffeeIT** [comment]
@msingleton Works perfectly, thanks so much!
