### ISSUE TITLE
Sometimes I am not getting the Survey after completing the survey with no limit 

### ISSUE THREAD

**Issue by Monika-Paliwal** [iteratehq/iterate-android#70]
Firstly I have initialised the Iterate 
`Iterate.init(this, API_Key, useEncryptedSharedPreferences = false)`
Then I have send Iterate Event 
```
  Iterate.sendEvent(
            Event_Name,
            supportFragmentManager
        )
```
When I published the survey from iterate but it's not showing in my app because previously I have completed the survey and sometimes it's showing properly, can you please help me out how can we show the survey every time because we have added no limit from Iterate survey.

**Comment by msingleton** [comment]
@Monika-Paliwal hey there, can you reach out to support@iteratehq.com or use our on-site chat to help fix the issue? Thanks
