### ISSUE TITLE
[Bug] Button corner radius not respected in Android SDK

### ISSUE THREAD

**Issue by florianPOLARSTEPS** [iteratehq/iterate-android#73]
# Description

Iterate SDK version: [v1.1.8](https://github.com/iteratehq/iterate-android/releases/tag/v1.1.8)

We can configure a corner radius for buttons used throughout surveys with iterate in the Survey editor. This works fine for the actual survey, but this setting is ignored for the prompt. 

<img width="463" alt="Screenshot 2024-03-04 at 10 59 53" src="https://github.com/iteratehq/iterate-android/assets/21218132/e6f4a76f-83e8-4765-88c8-de347287243f">

| Survey editor | Android app |
| --- | --- |
| <img width="401" alt="Screenshot 2024-03-04 at 11 04 19" src="https://github.com/iteratehq/iterate-android/assets/21218132/d831e8c0-f00b-45ed-a683-9df0fb623504"> | ![prompt](https://github.com/iteratehq/iterate-android/assets/21218132/af167849-bac5-4d00-8800-d4607839631a) |

# Expected behavior

- All settings that can be configured via the survey editor, are consumed and applied by the Android sdk.

**Comment by msingleton** [comment]
@florianPOLARSTEPS apologies for the delay! Adding this in now
