### ISSUE TITLE
[Feature request] Transitions for opening/exiting the survey screen

### ISSUE THREAD

**Issue by florianPOLARSTEPS** [iteratehq/iterate-android#74]
# Description

It would be nice if we could somehow configure the enter transitions (and exit transitions) for the Survey screen from the client side. 
Currently, the survey screen pops in without any transition in the Android SDK. 
Using the IOS sdk, at least it opens up with a default IOS style transition which feels more natural than the Android SDK.

**Comment by msingleton** [comment]
Thanks @florianPOLARSTEPS, I've added the request to our internal tracking. Going to close this issue for now but will ping you if there's any movement on it
